# Generated by Django 5.0.4 on 2024-04-29 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20240428_0428'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.PositiveBigIntegerField(max_length=20)),
                ('Name', models.CharField(max_length=255)),
                ('Created_by', models.PositiveBigIntegerField(max_length=20)),
                ('Created_at', models.DateTimeField()),
                ('Updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.PositiveBigIntegerField(max_length=20)),
                ('Property_key', models.CharField(max_length=255)),
                ('Sector', models.PositiveBigIntegerField(max_length=255)),
                ('Owner', models.PositiveBigIntegerField(max_length=20)),
                ('Property_Type', models.PositiveBigIntegerField(max_length=20)),
                ('Plot_No', models.CharField(max_length=255)),
                ('Society', models.PositiveBigIntegerField(max_length=20)),
                ('Street_No', models.CharField(max_length=255)),
                ('Phase', models.CharField(max_length=255)),
                ('Gali_No', models.CharField(max_length=255)),
                ('Society_Sector', models.CharField(max_length=255)),
                ('Flat_No', models.CharField(max_length=255)),
                ('Block_No', models.CharField(max_length=255)),
                ('Created_by', models.PositiveBigIntegerField(max_length=20)),
                ('Created_at', models.DateTimeField()),
                ('Updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Property_Bills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.PositiveBigIntegerField(max_length=20)),
                ('Consumer_ID', models.CharField(max_length=255)),
                ('Bill_Type', models.PositiveBigIntegerField(max_length=20)),
                ('Property_key', models.CharField(max_length=255)),
                ('Created_at', models.DateTimeField()),
                ('Updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Property_meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.PositiveBigIntegerField(max_length=20)),
                ('Key', models.CharField(max_length=255)),
                ('Value', models.TextField()),
                ('Property_ID', models.PositiveBigIntegerField(max_length=20)),
                ('Edit_by', models.PositiveBigIntegerField(max_length=20)),
                ('Created_at', models.DateTimeField()),
                ('Updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Property_Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.PositiveBigIntegerField(max_length=20)),
                ('Owner_Name', models.CharField(max_length=255)),
                ('CNIC', models.CharField(max_length=255)),
                ('Edit_by', models.BigIntegerField(max_length=20)),
                ('Created_at', models.DateTimeField()),
                ('Uploaded_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Property_Owner_meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.BigIntegerField(max_length=20)),
                ('Key', models.CharField(max_length=255)),
                ('Value', models.TextField()),
                ('Owner_ID', models.PositiveBigIntegerField(max_length=20)),
                ('Edit_by', models.PositiveBigIntegerField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Property_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.PositiveBigIntegerField(max_length=20)),
                ('Name', models.CharField(max_length=255)),
                ('Created_at', models.DateTimeField()),
                ('Updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.PositiveBigIntegerField(max_length=20)),
                ('Name', models.CharField(max_length=255)),
                ('Zone_ID', models.PositiveBigIntegerField(max_length=20)),
                ('Created_by', models.PositiveBigIntegerField(max_length=20)),
                ('Created_at', models.DateTimeField()),
                ('Updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Society',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.PositiveBigIntegerField(max_length=20)),
                ('Image', models.TextField()),
                ('Name', models.CharField(max_length=255)),
                ('Created_by', models.PositiveBigIntegerField(max_length=20)),
                ('Created_at', models.DateTimeField()),
                ('Updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.PositiveBigIntegerField(max_length=20)),
                ('Name', models.CharField(max_length=255)),
                ('Created_by', models.PositiveBigIntegerField(max_length=20)),
                ('Created_at', models.DateTimeField()),
                ('Updated_at', models.DateTimeField()),
            ],
        ),
    ]
